version: "3.3"
services:
  web:
    build:
      context: .
      dockerfile: "./dockerfile/Dockerfile.web"
    container_name: aria2-web
    ports:
      - "8888:8888"
    restart: unless-stopped
  daemon:
    build:
      context: .
      dockerfile: "./dockerfile/Dockerfile.daemon"
    container_name: aria2-daemon
    ports:
      - "6800:6800"
    volumes:
      - ./downloads:/aria2/downloads
    restart: unless-stopped
